version: "3.5"

services:
  db:
    image: postgres:16-alpine
    container_name: "${POSTGRES_CONTAINER_NAME}"

    volumes:
      - "${POSTGRES_DOCKER_VOLUME}:/var/lib/postgresql/data/"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

    restart: always

networks:
  default:
    driver: bridge
    name: "${DOCKER_NETWORK}"